import org.gradle.api.tasks.testing.logging.*

allprojects {
  plugins.withType(JavaPlugin) {
    dependencies {
      testImplementation libs.randomizedtesting.jupiter
      testImplementation libs.junit.jupiter
      testRuntimeOnly libs.junit.platform.launcher
    }

    test {
      maxParallelForks = propertyOrDefault("tests.jvms",
          (int) Math.max(1, Math.min(Runtime.runtime.availableProcessors() / 2.0, 4.0))) as Integer

      useJUnitPlatform()

      systemProperty "junit.jupiter.execution.parallel.enabled", "true"
      systemProperty "junit.jupiter.execution.parallel.mode.default", "same_thread"
      systemProperty "junit.jupiter.execution.parallel.mode.classes.default", "concurrent"

      minHeapSize = propertyOrDefault("tests.minheapsize", "256m")
      maxHeapSize = propertyOrDefault("tests.heapsize", "512m")

      testLogging {
        events TestLogEvent.FAILED
        exceptionFormat = TestExceptionFormat.FULL
        showExceptions = true
        showCauses = true
        showStackTraces = true
        stackTraceFilters.clear()
        showStandardStreams = false
      }
    }
  }
}
