name: On Commit Checks

on: 
  pull_request:
    branches:
      - master

  push:
    branches:
      - master
      
permissions:
  contents: read

jobs:
  tests:
    name: gradle check (JDK ${{ matrix.java }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
    
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ '25' ]

    steps:
      - name: Git checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          java-package: jdk

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Tests (./gradlew ... check)
        run: ./gradlew --max-workers 4 check

      - name: Store failed test outputs
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: failed-test-outputs-${{ matrix.java }}
          path: '**/OUTPUT-*.txt'
